import localFont from "next/font/local";
import "./globals.css";

const jetBrains_Mono = localFont({
  src: "./fonts/JetBrainsMono-Regular.ttf",
  variable: "--font-jetBrains-mono",
  weight: "100 200 300 400 500 600 700 800",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={jetBrains_Mono.variable}>{children}</body>
    </html>
  );
}
